# This workflow will install Python dependencies,
# run tests and lint with a variety of Python versions/

name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U setuptools setuptools_scm pep517
          python3 -m pip install -e .[neural_networks]


      - name: Run tests
        run: |
         pip install pytest
         pip install pytest-cov
         pytest --cov=src/cortecs --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests
          name: codecov-umbrella
          verbose: true
